from types import MappingProxyType

securities_mutual_fund_umbrella_types_tr = MappingProxyType({
    "Tümü": "Tümü",
    "Borçlanma Araçları Şemsiye Fonu": "100",
    "Değişken Şemsiye Fonu": "101",
    "Fon Sepeti Şemsiye Fonu": "102",
    "Hisse Senedi Şemsiye Fonu": "104",
    "Karma Şemsiye Fonu": "110",
    "Katılım Şemsiye Fonu": "114",
    "Kıymetli Madenler Şemsiye Fonu": "105",
    "Para Piyasası Şemsiye Fonu": "107",
    "Serbest Şemsiye Fonu": "108",
})

securities_mutual_fund_umbrella_types_en = MappingProxyType({
    "All": "All",
    "Debt Securities Umbrella Fund": "100",
    "Fund of Funds Umbrella Fund": "102",
    "Hedge Umbrella Fund": "108",
    "Mixed Umbrella Fund": "110",
    "Money Market Umbrella Fund": "107",
    "Participation Umbrella Fund": "114",
    "Precious Metals Umbrella Fund": "105",
    "Stock Umbrella Fund": "104",
    "Variable Umbrella Fund": "101",
})

securities_mutual_fund_title_type_tr = MappingProxyType({
    "Tümü": "Tümü",
    "Agresif Değişken": "Agresif Değişken",
    "Alternatif": "Alternatif",
    "Altın": "Altın",
    "Borçlanma Araçları": "Borçlanma Araçları",
    "Çalışanlarına Yönelik": "Çalışanlarına Yönelik",
    "Çoklu Varlık": "Çoklu Varlık",
    "Değişken": "Değişken",
    "Döviz": "Döviz",
    "Döviz Cinsinden İhraç (Dolar)": "Döviz Cinsinden İhraç (Dolar)",
    "Döviz Cinsinden İhraç (Euro)": "Döviz Cinsinden İhraç (Euro)",
    "Emtia": "Emtia",
    "Endeks": "Endeks",
    "Endeks Hisse Senedi": "Endeks Hisse Senedi",
    "Eurobond": "Eurobond",
    "Fon Sepeti": "Fon Sepeti",
    "Gümüş": "Gümüş",
    "Hisse Senedi": "Hisse Senedi",
    "Hisse Senedi Yoğun": "Hisse Senedi Yoğun",
    "İştirak": "İştirak",
    "Karma": "Karma",
    "Katılım": "Katılım",
    "Kısa Vadeli": "Kısa Vadeli",
    "Kısa Vadeli Borçlanma Araçları": "Kısa Vadeli Borçlanma Araçları",
    "Kıymetli Madenler": "Kıymetli Madenler",
    "Kira Sertifikaları": "Kira Sertifikaları",
    "Koruma Amaçlı": "Koruma Amaçlı",
    "Mutlak Getiri Hedefli": "Mutlak Getiri Hedefli",
    "Orta Vadeli": "Orta Vadeli",
    "Orta Vadeli Borçlanma Araçları": "Orta Vadeli Borçlanma Araçları",
    "Özel": "Özel",
    "Para Piyasası": "Para Piyasası",
    "Sektör": "Sektör",
    "Serbest": "Serbest",
    "Uzun Vadeli": "Uzun Vadeli",
    "Uzun Vadeli Borçlanma Araçları": "Uzun Vadeli Borçlanma Araçları",
    "Yabancı": "Yabancı",
    "Yabancı Fon Sepeti": "Yabancı Fon Sepeti",
})

securities_mutual_fund_title_type_en = MappingProxyType({
    "All": "All",
    "Absolute Return Targeted": "Absolute Return Targeted",
    "Aggressive Variable": "Aggressive Variable",
    "Alternative": "Alternative",
    "Asset Management Fx Fund Basket": "Asset Management Fx Fund Basket",
    "Bonds And Bills": "Bonds And Bills",
    "Commodity": "Commodity",
    "Equity": "Equity",
    "Equity-Intensive Fund": "Equity-Intensive Fund",
    "Eurobond": "Eurobond",
    "For Employees": "For Employees",
    "Foreign": "Foreign",
    "Foreign Currency": "Foreign Currency",
    "Foreign Currency (DOLLAR)": "Foreign Currency (DOLLAR)",
    "Foreign Currency (EURO)": "Foreign Currency (EURO)",
    "Fund Basket": "Fund Basket",
    "Gold": "Gold",
    "Independent": "Independent",
    "Index": "Index",
    "Index Equity": "Index Equity",
    "Lease Certificates": "Lease Certificates",
    "Long-Term": "Long-Term",
    "Long-Term Bonds And Bills": "Long-Term Bonds And Bills",
    "Medium-Term": "Medium-Term",
    "Medium-Term Bonds And Bills": "Medium-Term Bonds And Bills",
    "Mixed": "Mixed",
    "Money Market": "Money Market",
    "Multi Asset": "Multi Asset",
    "Participation": "Participation",
    "Precious Metals": "Precious Metals",
    "Private": "Private",
    "Protection Targeted": "Protection Targeted",
    "Sector": "Sector",
    "Share": "Share",
    "Short-Term": "Short-Term",
    "Short-Term Bonds And Bills": "Short-Term Bonds And Bills",
    "Silver": "Silver",
    "Variable": "Variable",
})
