""""Schema validation"""

REQUIRED_FIELDS = {
    "FonKodu",
    "Tarih",
    "Fon Adı",
    "Fiyat",
    "TedavüldekiPaySayısı",
    "KişiSayısı",
    "Fon Toplam Değer",
    "Banka Bonosu (%)",
    "Diğer (%)",
    "Döviz Ödemeli Bono (%)",
    "Devlet Tahvili (%)",
    "Dövize Ödemeli Tahvil (%)",
    "Eurobonds (%)",
    "Finansman Bonosu (%)",
    "Fon Katılma Belgesi (%)",
    "Gayrı Menkul Sertifikası (%)",
    "Hazine Bonosu (%)",
    "Hisse Senedi (%)",
    "Kamu Dış Borçlanma Araçları (%)",
    "Katılım Hesabı (%)",
    "Kamu Kira Sertifikaları (%)",
    "Kıymetli Madenler (%)",
    "Özel Sektör Kira Sertifikaları (%)",
    "Özel Sektör Tahvili (%)",
    "Repo (%)",
    "Türev Araçları (%)",
    "TPP (%)",
    "Ters-Repo (%)",
    "Varlığa Dayalı Menkul Kıymetler (%)",
    "Vadeli Mevduat (%)",
    "Yabancı Borçlanma Aracı (%)",
    "Yabancı Hisse Senedi (%)",
    "Yabancı Menkul Kıymet (%)",
}
